---

vlans: "2-20,99"

trunk_vlans: "2-20"
native: 99

named_spine_vlans:
  - { vlan_id: 10, name: test_segment }
  - { vlan_id: 20, name: peer_keepalive }
  - { vlan_id: 99, name: native }


default_trunk_interfaces:
  - Ethernet1/1
  - Ethernet1/2
  - Ethernet2/1

pkl_interfaces:
  - Ethernet2/12

logical_interfaces_to_create:
  - vlan10
  - vlan20

vrfs:
  - keepalive

pkl_link:
  vrf: keepalive
  interface: vlan20

hsrp:
  - { interface: vlan10, vip: 10.1.10.1, group: 10 }
  - { interface: vlan20, vip: 10.1.20.1, group: 20 }

portchannels:
  10:
    members:
      - Ethernet1/1
      - Ethernet1/2
    mode: active
  11:
    members:
      - Ethernet2/1
    mode: active
  12:
    members:
      - Ethernet2/12
    mode: active

