---

- name: interface testing
  hosts: n9k1
  connection: local
  gather_facts: no


  tasks:

    # Ensure an interface is a Layer 3 port and that it has the proper description
    - nxos_interface: interface=Ethernet1/1 description='Configured by Ansible' mode=layer3 host={{ inventory_hostname }}

    # Admin down an interface
    - nxos_interface: interface=Ethernet2/1 host={{ inventory_hostname }} admin_state=down

    # Remove all loopback interfaces
    - nxos_interface: interface=loopback state=absent host={{ inventory_hostname }}

    # Remove all logical interfaces
    - nxos_interface: interface={{ item }} state=absent host={{ inventory_hostname }}
      with_items:
        - loopback
        - portchannel
        - svi

    # Admin up all ethernet interfaces
    - nxos_interface: interface=ethernet host={{ inventory_hostname }} admin_state=up

    # Admin down ALL interfaces (physical and logical)
    - nxos_interface: interface=all host={{ inventory_hostname }} admin_state=down
