---

- name: get neighbors testing
  hosts: n9k1
  connection: local
  gather_facts: no


  tasks:

    # retrieve details info and stats on an interface (from 'show interface')
    - nxos_get_interface: interface=Ethernet1/1 host={{ inventory_hostname }}
