---

- name: copy testing
  hosts: n9k1
  connection: local
  gather_facts: no


  tasks:

    # Ensure directory is created on target device
    - nxos_dir: path='bootflash:new_config_dir' host={{ inventory_hostname }} state=present

    # Ensure directory is not on target device
    - nxos_dir: path='bootflash:new_config_dir' host={{ inventory_hostname }} state=absent

    # Ensure file is not on target device
    - nxos_dir: path='bootflash:switch_config1.cfg' host={{ inventory_hostname }} state=absent
