---
- name: get neighbor data
  hosts: n9k-1
  connection: local
  gather_facts: no

  tasks:
    - name: get neighbors
      nxos_get_neighbors: type=cdp host={{ inventory_hostname }}
      register: my_neighbors

    - name: print data to file
      template: src=/nxos-ansible/templates/neighbors.j2 dest=/nxos-ansible/myscripts/neighbors.json
